spring:
  application:
    name: crm-backend

server:
  servlet:
    context-path: /api/v1

datasource:
   url: ${SPRING_DATASOURCE_URL}
   username: ${SPRING_DATASOURCE_USERNAME}
   password: ${SPRING_DATASOURCE_PASSWORD}

jpa:
  hibernate:
  ddl-auto: validate

jwt:
  access:
    secret: ${JWT_ACCESS_SECRET}
    expiration: ${JWT_ACCESS_EXPIRATION}
  refresh:
    secret: ${JWT_REFRESH_SECRET}
    expiration: ${JWT_REFRESH_EXPIRATION}  